title: Sushant
logo: "/profile.png?raw=true"
description: >
Freasher
<br><br>
<a href="mailto:mitthujangra4229@gmail.com">mitthujangra4229@gmail.com </a>
<br>
<a href="https://www.linkedin.com/in/sushant-jangra-0140881b0/">LinkedIn Profile</a>
<br>
<a href="https://github.com/SushantJangra/">Github</a>
theme: jekyll-theme-minimal
